env:
  browser: true
  es6: true
  jest: true
  jquery: true
extends: 'eslint:recommended'
parser:
  '@typescript-eslint/parser'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  quotes:
    - error
    - single
  comma-dangle:
    - error
    - always-multiline
    - functions: never
  object-curly-spacing:
    - error
    - always
  semi:
    - error
    - always
  no-console:
    - error
  no-extra-semi:
    - error
